-- INSERTS 

-- Colaborador
INSERT INTO T_AUMO_COLABORADOR (DELETED, DT_CRIACAO, NM_COLABORADOR, TP_COLABORADOR) VALUES (0, SYSDATE, 'João Silva', 'ADMIN');

INSERT INTO T_AUMO_COLABORADOR (DELETED, DT_CRIACAO, NM_COLABORADOR, TP_COLABORADOR) VALUES (0, SYSDATE, 'Maria Oliveira', 'OPERADOR');

INSERT INTO T_AUMO_COLABORADOR (DELETED, DT_CRIACAO, NM_COLABORADOR, TP_COLABORADOR) VALUES (0, SYSDATE, 'Carlos Lima', 'OPERADOR');

INSERT INTO T_AUMO_COLABORADOR (DELETED, DT_CRIACAO, NM_COLABORADOR, TP_COLABORADOR) VALUES (0, SYSDATE, 'Ana Souza', 'ADMIN');

INSERT INTO T_AUMO_COLABORADOR (DELETED, DT_CRIACAO, NM_COLABORADOR, TP_COLABORADOR) VALUES (0, SYSDATE, 'Lucas Rocha', 'OPERADOR');

INSERT INTO T_AUMO_COLABORADOR (DELETED, DT_CRIACAO, NM_COLABORADOR, TP_COLABORADOR) VALUES (0, SYSDATE, 'Fernanda Dias', 'ADMIN');

INSERT INTO T_AUMO_COLABORADOR (DELETED, DT_CRIACAO, NM_COLABORADOR, TP_COLABORADOR) VALUES (0, SYSDATE, 'Ricardo Alves', 'OPERADOR');

INSERT INTO T_AUMO_COLABORADOR (DELETED, DT_CRIACAO, NM_COLABORADOR, TP_COLABORADOR) VALUES (0, SYSDATE, 'Juliana Martins', 'OPERADOR');

INSERT INTO T_AUMO_COLABORADOR (DELETED, DT_CRIACAO, NM_COLABORADOR, TP_COLABORADOR) VALUES (0, SYSDATE, 'Bruno Ferreira', 'ADMIN');

INSERT INTO T_AUMO_COLABORADOR (DELETED, DT_CRIACAO, NM_COLABORADOR, TP_COLABORADOR) VALUES (0, SYSDATE, 'Patrícia Lima', 'OPERADOR');



-- Autentica colaborador
INSERT INTO T_AUMO_AUTENTICA_COLABORADOR (ID_COLABORADOR, EMAIL, SENHA) VALUES (1, 'joao.silva@aumo.com', 'senha123');

INSERT INTO T_AUMO_AUTENTICA_COLABORADOR (ID_COLABORADOR, EMAIL, SENHA) VALUES (2, 'maria.oliveira@aumo.com', 'senha123');

INSERT INTO T_AUMO_AUTENTICA_COLABORADOR (ID_COLABORADOR, EMAIL, SENHA) VALUES (3, 'carlos.lima@aumo.com', 'senha123');

INSERT INTO T_AUMO_AUTENTICA_COLABORADOR (ID_COLABORADOR, EMAIL, SENHA) VALUES (4, 'ana.souza@aumo.com', 'senha123');

INSERT INTO T_AUMO_AUTENTICA_COLABORADOR (ID_COLABORADOR, EMAIL, SENHA) VALUES (5, 'lucas.rocha@aumo.com', 'senha123');

INSERT INTO T_AUMO_AUTENTICA_COLABORADOR (ID_COLABORADOR, EMAIL, SENHA) VALUES (6, 'fernanda.dias@aumo.com', 'senha123');

INSERT INTO T_AUMO_AUTENTICA_COLABORADOR (ID_COLABORADOR, EMAIL, SENHA) VALUES (7, 'ricardo.alves@aumo.com', 'senha123');

INSERT INTO T_AUMO_AUTENTICA_COLABORADOR (ID_COLABORADOR, EMAIL, SENHA) VALUES (8, 'juliana.martins@aumo.com', 'senha123');

INSERT INTO T_AUMO_AUTENTICA_COLABORADOR (ID_COLABORADOR, EMAIL, SENHA) VALUES (9, 'bruno.ferreira@aumo.com', 'senha123');

INSERT INTO T_AUMO_AUTENTICA_COLABORADOR (ID_COLABORADOR, EMAIL, SENHA) VALUES (10, 'patricia.lima@aumo.com', 'senha123');



-- Sessão colaboraborador
INSERT INTO T_AUMO_SESSAO_COLABORADOR (ID_COLABORADOR, TOKEN_SESSAO, DT_LOGIN, ST_SESSAO) VALUES (1, 'uuid-1', SYSDATE, 'ATIVA');

INSERT INTO T_AUMO_SESSAO_COLABORADOR (ID_COLABORADOR, TOKEN_SESSAO, DT_LOGIN, ST_SESSAO) VALUES (2, 'uuid-2', SYSDATE, 'ATIVA');

INSERT INTO T_AUMO_SESSAO_COLABORADOR (ID_COLABORADOR, TOKEN_SESSAO, DT_LOGIN, ST_SESSAO) VALUES (3, 'uuid-3', SYSDATE, 'ATIVA');

INSERT INTO T_AUMO_SESSAO_COLABORADOR (ID_COLABORADOR, TOKEN_SESSAO, DT_LOGIN, ST_SESSAO) VALUES (4, 'uuid-4', SYSDATE, 'ATIVA');

INSERT INTO T_AUMO_SESSAO_COLABORADOR (ID_COLABORADOR, TOKEN_SESSAO, DT_LOGIN, ST_SESSAO) VALUES (5, 'uuid-5', SYSDATE, 'ATIVA');

INSERT INTO T_AUMO_SESSAO_COLABORADOR (ID_COLABORADOR, TOKEN_SESSAO, DT_LOGIN, ST_SESSAO) VALUES (6, 'uuid-6', SYSDATE, 'ATIVA');

INSERT INTO T_AUMO_SESSAO_COLABORADOR (ID_COLABORADOR, TOKEN_SESSAO, DT_LOGIN, ST_SESSAO) VALUES (7, 'uuid-7', SYSDATE, 'ATIVA');

INSERT INTO T_AUMO_SESSAO_COLABORADOR (ID_COLABORADOR, TOKEN_SESSAO, DT_LOGIN, ST_SESSAO) VALUES (8, 'uuid-8', SYSDATE, 'ATIVA');

INSERT INTO T_AUMO_SESSAO_COLABORADOR (ID_COLABORADOR, TOKEN_SESSAO, DT_LOGIN, ST_SESSAO) VALUES (9, 'uuid-9', SYSDATE, 'ATIVA');

INSERT INTO T_AUMO_SESSAO_COLABORADOR (ID_COLABORADOR, TOKEN_SESSAO, DT_LOGIN, ST_SESSAO) VALUES (10, 'uuid-10', SYSDATE, 'ATIVA');



-- Linha
INSERT INTO T_AUMO_LINHA (DELETED, DT_CRIACAO, NM_LINHA, NR_LINHA, ST_LINHA) VALUES (0, SYSDATE, 'Linha Azul', 1, 'NORMAL');

INSERT INTO T_AUMO_LINHA (DELETED, DT_CRIACAO, NM_LINHA, NR_LINHA, ST_LINHA) VALUES (0, SYSDATE, 'Linha Vermelha', 2, 'PARCIAL');

INSERT INTO T_AUMO_LINHA (DELETED, DT_CRIACAO, NM_LINHA, NR_LINHA, ST_LINHA) VALUES (0, SYSDATE, 'Linha Verde', 3, 'NORMAL');

INSERT INTO T_AUMO_LINHA (DELETED, DT_CRIACAO, NM_LINHA, NR_LINHA, ST_LINHA) VALUES (0, SYSDATE, 'Linha Amarela', 4, 'INTERROMPIDO');

INSERT INTO T_AUMO_LINHA (DELETED, DT_CRIACAO, NM_LINHA, NR_LINHA, ST_LINHA) VALUES (0, SYSDATE, 'Linha Lilás', 5, 'NORMAL');



-- Estação
INSERT INTO T_AUMO_ESTACAO (ID_LINHA, DELETED, DT_CRIACAO, NM_ESTACAO, ST_ESTACAO, HR_FUNCIONAMENTO_INICIO, HR_FUNCIONAMENTO_FIM)
VALUES (1, 0, SYSDATE, 'Estação Central', 'NORMAL', TO_DATE('05:00','HH24:MI'), TO_DATE('23:00','HH24:MI'));

INSERT INTO T_AUMO_ESTACAO (ID_LINHA, DELETED, DT_CRIACAO, NM_ESTACAO, ST_ESTACAO, HR_FUNCIONAMENTO_INICIO, HR_FUNCIONAMENTO_FIM) 
VALUES (2, 0, SYSDATE, 'Estação Leste', 'PARCIAL', TO_DATE('06:00','HH24:MI'), TO_DATE('22:00','HH24:MI'));

INSERT INTO T_AUMO_ESTACAO (ID_LINHA, DELETED, DT_CRIACAO, NM_ESTACAO, ST_ESTACAO, HR_FUNCIONAMENTO_INICIO, HR_FUNCIONAMENTO_FIM) 
VALUES (3, 0, SYSDATE, 'Estação Norte', 'NORMAL', TO_DATE('05:30','HH24:MI'), TO_DATE('23:30','HH24:MI'));

INSERT INTO T_AUMO_ESTACAO (ID_LINHA, DELETED, DT_CRIACAO, NM_ESTACAO, ST_ESTACAO, HR_FUNCIONAMENTO_INICIO, HR_FUNCIONAMENTO_FIM) 
VALUES (4, 0, SYSDATE, 'Estação Sul', 'INTERROMPIDO', TO_DATE('06:00','HH24:MI'), TO_DATE('21:00','HH24:MI'));

INSERT INTO T_AUMO_ESTACAO (ID_LINHA, DELETED, DT_CRIACAO, NM_ESTACAO, ST_ESTACAO, HR_FUNCIONAMENTO_INICIO, HR_FUNCIONAMENTO_FIM) 
VALUES (5, 0, SYSDATE, 'Estação Oeste', 'NORMAL', TO_DATE('05:00','HH24:MI'), TO_DATE('23:00','HH24:MI'));

INSERT INTO T_AUMO_ESTACAO (ID_LINHA, DELETED, DT_CRIACAO, NM_ESTACAO, ST_ESTACAO, HR_FUNCIONAMENTO_INICIO, HR_FUNCIONAMENTO_FIM) 
VALUES (1, 0, SYSDATE, 'Estação Jardim', 'NORMAL', TO_DATE('05:00','HH24:MI'), TO_DATE('23:00','HH24:MI'));

INSERT INTO T_AUMO_ESTACAO (ID_LINHA, DELETED, DT_CRIACAO, NM_ESTACAO, ST_ESTACAO, HR_FUNCIONAMENTO_INICIO, HR_FUNCIONAMENTO_FIM) 
VALUES (2, 0, SYSDATE, 'Estação Vila', 'NORMAL', TO_DATE('05:00','HH24:MI'), TO_DATE('23:00','HH24:MI'));

INSERT INTO T_AUMO_ESTACAO (ID_LINHA, DELETED, DT_CRIACAO, NM_ESTACAO, ST_ESTACAO, HR_FUNCIONAMENTO_INICIO, HR_FUNCIONAMENTO_FIM) 
VALUES (3, 0, SYSDATE, 'Estação Cidade', 'PARCIAL', TO_DATE('05:00','HH24:MI'), TO_DATE('23:00','HH24:MI'));

INSERT INTO T_AUMO_ESTACAO (ID_LINHA, DELETED, DT_CRIACAO, NM_ESTACAO, ST_ESTACAO, HR_FUNCIONAMENTO_INICIO, HR_FUNCIONAMENTO_FIM) 
VALUES (4, 0, SYSDATE, 'Estação Parque', 'INTERROMPIDO', TO_DATE('05:00','HH24:MI'), TO_DATE('23:00','HH24:MI'));

INSERT INTO T_AUMO_ESTACAO (ID_LINHA, DELETED, DT_CRIACAO, NM_ESTACAO, ST_ESTACAO, HR_FUNCIONAMENTO_INICIO, HR_FUNCIONAMENTO_FIM) 
VALUES (5, 0, SYSDATE, 'Estação Campus', 'NORMAL', TO_DATE('05:00','HH24:MI'), TO_DATE('23:00','HH24:MI'));


-- Alerta
INSERT INTO T_AUMO_ALERTA (DELETED, DT_CRIACAO, DS_ALERTA, NM_ALERTA, NV_GRAVIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Interrupção causada por pane elétrica na rede de alimentação.', 'Pane elétrica', 'GRAVE', 1, 1);

INSERT INTO T_AUMO_ALERTA (DELETED, DT_CRIACAO, DS_ALERTA, NM_ALERTA, NV_GRAVIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Atraso previsto devido ao grande fluxo de passageiros.', 'Aviso de atraso', 'LEVE', 2, 2);

INSERT INTO T_AUMO_ALERTA (DELETED, DT_CRIACAO, DS_ALERTA, NM_ALERTA, NV_GRAVIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Serviço de manutenção agendado para melhorias na via.', 'Interrupção programada', 'MÉDIO', 3, 3);

INSERT INTO T_AUMO_ALERTA (DELETED, DT_CRIACAO, DS_ALERTA, NM_ALERTA, NV_GRAVIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Inundação causada por chuvas intensas, operação temporariamente suspensa.', 'Alagamento na linha', 'GRAVE', 4, 4);

INSERT INTO T_AUMO_ALERTA (DELETED, DT_CRIACAO, DS_ALERTA, NM_ALERTA, NV_GRAVIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Protesto nas proximidades causa lentidão nas operações.', 'Manifestação', 'MÉDIO', 5, 5);

INSERT INTO T_AUMO_ALERTA (DELETED, DT_CRIACAO, DS_ALERTA, NM_ALERTA, NV_GRAVIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Inspeção preventiva sendo realizada nos equipamentos.', 'Verificação técnica', 'LEVE', 1, 6);

INSERT INTO T_AUMO_ALERTA (DELETED, DT_CRIACAO, DS_ALERTA, NM_ALERTA, NV_GRAVIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Problema mecânico em trem exige retirada de circulação.', 'Falha mecânica', 'MÉDIO', 2, 7);

INSERT INTO T_AUMO_ALERTA (DELETED, DT_CRIACAO, DS_ALERTA, NM_ALERTA, NV_GRAVIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Colisão leve entre composições, sem vítimas, mas com impacto no tráfego.', 'Acidente', 'GRAVE', 3, 8);

INSERT INTO T_AUMO_ALERTA (DELETED, DT_CRIACAO, DS_ALERTA, NM_ALERTA, NV_GRAVIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Atos de vandalismo provocaram danos à infraestrutura.', 'Vandalismo', 'MÉDIO', 4, 9);

INSERT INTO T_AUMO_ALERTA (DELETED, DT_CRIACAO, DS_ALERTA, NM_ALERTA, NV_GRAVIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Alerta de precaução emitido para verificação de anomalias.', 'Aviso preventivo', 'LEVE', 5, 10);



-- Manutenção
INSERT INTO T_AUMO_MANUTENCAO (DELETED, DT_CRIACAO, NM_MANUTENCAO, DS_MANUTENCAO, NV_PRIORIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Troca de Trilhos', 'Substituição completa dos trilhos.', 'ALTA', 1, 1);

INSERT INTO T_AUMO_MANUTENCAO (DELETED, DT_CRIACAO, NM_MANUTENCAO, DS_MANUTENCAO, NV_PRIORIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Pintura', 'Pintura de estruturas da estação.', 'BAIXA', 2, 2);

INSERT INTO T_AUMO_MANUTENCAO (DELETED, DT_CRIACAO, NM_MANUTENCAO, DS_MANUTENCAO, NV_PRIORIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Limpeza', 'Limpeza geral programada.', 'BAIXA', 3, 3);

INSERT INTO T_AUMO_MANUTENCAO (DELETED, DT_CRIACAO, NM_MANUTENCAO, DS_MANUTENCAO, NV_PRIORIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Revisão elétrica', 'Verificação de cabos e fiação.', 'MÉDIA', 4, 4);

INSERT INTO T_AUMO_MANUTENCAO (DELETED, DT_CRIACAO, NM_MANUTENCAO, DS_MANUTENCAO, NV_PRIORIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Teste de segurança', 'Testes preventivos de segurança.', 'MÉDIA', 5, 5);

INSERT INTO T_AUMO_MANUTENCAO (DELETED, DT_CRIACAO, NM_MANUTENCAO, DS_MANUTENCAO, NV_PRIORIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Manutenção preventiva', 'Revisão completa de equipamentos.', 'ALTA', 1, 6);

INSERT INTO T_AUMO_MANUTENCAO (DELETED, DT_CRIACAO, NM_MANUTENCAO, DS_MANUTENCAO, NV_PRIORIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Limpeza especial', 'Higienização intensa.', 'MÉDIA', 2, 7);

INSERT INTO T_AUMO_MANUTENCAO (DELETED, DT_CRIACAO, NM_MANUTENCAO, DS_MANUTENCAO, NV_PRIORIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Ajuste de trilhos', 'Correções de alinhamento.', 'MÉDIA', 3, 8);

INSERT INTO T_AUMO_MANUTENCAO (DELETED, DT_CRIACAO, NM_MANUTENCAO, DS_MANUTENCAO, NV_PRIORIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Troca de cabos', 'Substituição de cabos de energia.', 'ALTA', 4, 9);

INSERT INTO T_AUMO_MANUTENCAO (DELETED, DT_CRIACAO, NM_MANUTENCAO, DS_MANUTENCAO, NV_PRIORIDADE, ID_LINHA, ID_ESTACAO)
VALUES (0, SYSDATE, 'Verificação de sinalização', 'Revisão dos painéis informativos.', 'BAIXA', 5, 10);



-- Mensagem de contato
INSERT INTO T_AUMO_MS_CONTATO (DELETED, DT_CRIACAO, NM_CONTATO, EMAIL_CONTATO, MS_CONTATO)
VALUES (0, SYSDATE, 'Pedro Almeida', 'pedro@email.com', 'Gostaria de sugerir melhorias no app.');

INSERT INTO T_AUMO_MS_CONTATO (DELETED, DT_CRIACAO, NM_CONTATO, EMAIL_CONTATO, MS_CONTATO) 
VALUES (0, SYSDATE, 'Marina Torres', 'marina@email.com', 'Problemas na estação Leste.');

INSERT INTO T_AUMO_MS_CONTATO (DELETED, DT_CRIACAO, NM_CONTATO, EMAIL_CONTATO, MS_CONTATO) 
VALUES (0, SYSDATE, 'Rogério Matos', 'rogerio@email.com', 'App fecha sozinho.');

INSERT INTO T_AUMO_MS_CONTATO (DELETED, DT_CRIACAO, NM_CONTATO, EMAIL_CONTATO, MS_CONTATO) 
VALUES (0, SYSDATE, 'Juliana Cruz', 'juliana@email.com', 'Não recebo notificações.');

INSERT INTO T_AUMO_MS_CONTATO (DELETED, DT_CRIACAO, NM_CONTATO, EMAIL_CONTATO, MS_CONTATO) 
VALUES (0, SYSDATE, 'Diego Costa', 'diego@email.com', 'Sugestão de novo recurso.');



-- Feedback
INSERT INTO T_AUMO_FEEDBACK (MS_FEEDBACK, NV_SATISFACAO) VALUES ('Excelente experiência com o app!', 'ALTA');
INSERT INTO T_AUMO_FEEDBACK (MS_FEEDBACK, NV_SATISFACAO) VALUES ('Achei a interface um pouco confusa.', 'MÉDIA');
INSERT INTO T_AUMO_FEEDBACK (MS_FEEDBACK, NV_SATISFACAO) VALUES ('Não consegui acessar minha conta.', 'BAIXA');
INSERT INTO T_AUMO_FEEDBACK (MS_FEEDBACK, NV_SATISFACAO) VALUES ('App rápido e funcional.', 'ALTA');
INSERT INTO T_AUMO_FEEDBACK (MS_FEEDBACK, NV_SATISFACAO) VALUES ('Seria bom ter um modo escuro.', 'MÉDIA');



-- Logs de atividade
INSERT INTO T_AUMO_LOG_ATIVIDADE (TOKEN_SESSAO, DT_CRIACAO, ACAO_REALIZADA)
VALUES ('uuid-1', SYSDATE, 'Login realizado');

INSERT INTO T_AUMO_LOG_ATIVIDADE (TOKEN_SESSAO, DT_CRIACAO, ACAO_REALIZADA)
VALUES  ('uuid-2', SYSDATE, 'Edição de alerta');

INSERT INTO T_AUMO_LOG_ATIVIDADE (TOKEN_SESSAO, DT_CRIACAO, ACAO_REALIZADA)
VALUES  ('uuid-3', SYSDATE, 'Criação de estação');

INSERT INTO T_AUMO_LOG_ATIVIDADE (TOKEN_SESSAO, DT_CRIACAO, ACAO_REALIZADA)
VALUES  ('uuid-4', SYSDATE, 'Logout realizado');

INSERT INTO T_AUMO_LOG_ATIVIDADE (TOKEN_SESSAO, DT_CRIACAO, ACAO_REALIZADA)
VALUES  ('uuid-5', SYSDATE, 'Alteração de status de linha');

INSERT INTO T_AUMO_LOG_ATIVIDADE (TOKEN_SESSAO, DT_CRIACAO, ACAO_REALIZADA)
VALUES  ('uuid-6', SYSDATE, 'Visualização de feedbacks');

INSERT INTO T_AUMO_LOG_ATIVIDADE (TOKEN_SESSAO, DT_CRIACAO, ACAO_REALIZADA)
VALUES  ('uuid-7', SYSDATE, 'Login realizado');

INSERT INTO T_AUMO_LOG_ATIVIDADE (TOKEN_SESSAO, DT_CRIACAO, ACAO_REALIZADA)
VALUES  ('uuid-8', SYSDATE, 'Registro de manutenção');

INSERT INTO T_AUMO_LOG_ATIVIDADE (TOKEN_SESSAO, DT_CRIACAO, ACAO_REALIZADA)
VALUES  ('uuid-9', SYSDATE, 'Consulta de mensagens');

INSERT INTO T_AUMO_LOG_ATIVIDADE (TOKEN_SESSAO, DT_CRIACAO, ACAO_REALIZADA)
VALUES  ('uuid-10', SYSDATE, 'Atualização de colaborador');
