-- SELECT SIMPLES

SELECT * FROM T_AUMO_COLABORADOR;

SELECT * FROM T_AUMO_AUTENTICA_COLABORADOR;

SELECT * FROM T_AUMO_SESSAO_COLABORADOR;

SELECT * FROM T_AUMO_LINHA;

SELECT * FROM T_AUMO_ESTACAO;

SELECT * FROM T_AUMO_ALERTA;

SELECT * FROM T_AUMO_MANUTENCAO;

SELECT * FROM T_AUMO_MS_CONTATO;

SELECT * FROM T_AUMO_FEEDBACK;

SELECT * FROM T_AUMO_LOG_ATIVIDADE;



-- Tabela alvo para consultas: T_AUMO_ALERTA

-- SELECT COM CLASSIFICAÇÃO (ORDER BY)
SELECT * FROM T_AUMO_ALERTA ORDER BY DT_CRIACAO DESC;

-- SELECT COM FUNÇÃO NUMÉRICA (COUNT)
SELECT COUNT(*) AS TOTAL_ALERTAS_GRAVES FROM T_AUMO_ALERTA WHERE NV_GRAVIDADE = 'GRAVE';

-- SELECT COM AGRUPAMENTO (GROUP BY)
SELECT NV_GRAVIDADE, COUNT(*) AS TOTAL_POR_GRAVIDADE FROM T_AUMO_ALERTA GROUP BY NV_GRAVIDADE;

-- SELECT COM SUB CONSULTA (SUBQUERY)
SELECT * FROM T_AUMO_ALERTA WHERE ID_ALERTA IN (SELECT ID_ALERTA FROM T_AUMO_ALERTA WHERE NV_GRAVIDADE = 'GRAVE');

-- SELECT COM JUNÇÃO DE TABELAS (JOIN)
SELECT A.ID_ALERTA, A.NM_ALERTA, A.NV_GRAVIDADE, E.NM_ESTACAO FROM T_AUMO_ALERTA A JOIN T_AUMO_ESTACAO E ON A.ID_ESTACAO = E.ID_ESTACAO;

-- SELECT COM FILTRAGEM DE DADOS
SELECT * FROM T_AUMO_ALERTA WHERE ID_ALERTA = 1;


